services:
  - type: web
    name: pawfect-api
    env: docker
    dockerfilePath: ./Pawfect-API/Dockerfile
    dockerContext: ./Pawfect-API
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: pawfect-notifications
    env: docker
    dockerfilePath: ./Pawfect-Notifications/Dockerfile
    dockerContext: ./Pawfect-Notifications
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: pawfect-messenger
    env: docker
    dockerfilePath: ./Pawfect-Messenger/Dockerfile
    dockerContext: ./Pawfect-Messenger
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
